#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/yoradio-docs/docs/myoptions-generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,1,2,4,7,9,73,42,43,54,55,56,58,67&i=1,2,3,4,15,16,17,28,29,30,31,32,33,41&v=9,10,8,255,6,7,5,2,1,42,41,40,39,14 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */
/* !!! Do not be alarmed by some #defines missing. Default values are not included in this file. !!! */
/* !!! Values of 255 must be edited before using (except I2S_DOUT 255 which is used to disable I2S Sound). !!! */

#define ARDUINO_ESP32S3_DEV

#define L10N_LANGUAGE RU

#define DSP_MODEL DSP_SSD1322
#define TFT_DC 9
#define TFT_CS 10
#define TFT_RST 8
#define BRIGHTNESS_PIN 255
#define NEXTION_RX 255
#define NEXTION_TX 255

#define I2S_LRC 5
#define I2S_DOUT 6
#define I2S_BCLK 7
#define I2S_MCLK 16
#define I2S_INTERNAL false


#define ENC_BTNR 2
#define ENC_BTNL 1
#define ENC_BTNB 42

#define ENC2_BTNR 41
#define ENC2_BTNL 40
#define ENC2_BTNB 39

#define IR_PIN			14
#define IR_TIMEOUT       20

// dodać jeśli chcesz wyłaczyć diodę RGB:
#define USE_BUILTIN_LED false
#define LED_BUILTIN_S3 255

// dodać jesli wyświetlacz to SSD1322 i chcesz mieć odcienie szarości:
#define SSD1322_GRAYSCALE true

// dodać jeśli wyświetlacz to SSD1322 i projekt to Virtuoso:
#define BITRATE_FULL false //---wyłączenie wskaznika BitrateFull (używamy prostego)
#define EXT_WEATHER false //---skrocone informacje pogodowe
#define SDC_CS 255
#define TS_MODEL TS_MODEL_UNDEFINED

#endif
